In [8]:
import numpy as np
a = np.arange(0, 24).reshape(6,4)
b=np.array([1,2,3,4])
print(a,b)
print(a-b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] [1 2 3 4]
[[-1 -1 -1 -1]
 [ 3  3  3  3]
 [ 7  7  7  7]
 [11 11 11 11]
 [15 15 15 15]
 [19 19 19 19]]


In [7]:
for i in range(5):
    print(i)

0
1
2
3
4
