In [64]:
import numpy as np

In [65]:
np.__version__

'1.15.4'

In [66]:
#the diffrent in range and arange
#range(start,end,step) default:start 0 step 1
#range return a list bu not a numpy array returned from ndarray
a1=list(range(2,8,2))
b1=np.arange(5)
print(a1,b1)


[2, 4, 6] [0 1 2 3 4]


In [67]:
#numpy.full_like(array, fill_value, dtype=None, order='K', subok=True)
#create a numpy array that shape like a
a2=[[1,2],[3,4]]
a2=np.array(a2)
a2=np.full_like(a2,True,dtype=bool)
print(a2)
#full((shapeX,shapeY),fill_value,dtype=None)
np.full((3, 3), True, dtype=bool)

[[ True  True]
 [ True  True]]


array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [68]:
arr3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr3%2==1)
arr3[arr3%2==1]

[False  True False  True False  True False  True False  True]


array([1, 3, 5, 7, 9])

In [69]:
arr4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr4[arr4%2==1]=0
print(arr4)

[0 0 2 0 4 0 6 0 8 0]


In [70]:
#np.where(condition, x, y)
#满足条件(condition)，输出x，不满足输出y。
a5=np.arange(10)
a5_1=np.arange(10,20)
b5=np.where(a5%2==1,1,-1)
c5=np.where(a5%2==1,1,a5_1)#引用a5的意思是不满足条件直接按照a5_1的对应位置的值输出
print(a5,b5,c5)

[0 1 2 3 4 5 6 7 8 9] [-1  1 -1  1 -1  1 -1  1 -1  1] [10  1 12  1 14  1 16  1 18  1]


In [71]:
a6=[[1,2,3],[4,5,6]]
b6=[[6,7,8],[2,5,11]]
np.intersect1d(a6,b6)

array([2, 5, 6])

In [72]:
a7=np.array([[1,2,3],[4,5,6]])
b7=np.array([2,3,4])
np.setdiff1d(a7,b7)

array([1, 5, 6])

In [73]:
a8 = np.array([1,2,3,2,3,4,3,4,5,6])
b8 = np.array([7,2,10,2,7,4,9,4,9,8])
print(a8==b8)
np.where(a8==b8)

[False  True False  True False  True False  True False False]


(array([1, 3, 5, 7], dtype=int64),)

In [74]:
a9=np.array([7,2,10,2,7,4,9,4,9,8])
a9[(a9 >= 5) & (a9 <= 10)]

array([ 7, 10,  7,  9,  9,  8])

In [75]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]]) 

[1 4 5]


In [76]:
a10=np.arange(9).reshape(3,3)


In [77]:
b10=np.random.uniform(0.1,0.9,size=(3,3))
np.set_printoptions(precision=5)
b10

array([[0.25174, 0.42862, 0.57574],
       [0.67327, 0.48951, 0.34767],
       [0.56195, 0.45337, 0.38774]])

In [78]:
np.set_printoptions(suppress=False)
b11=np.random.uniform(0.1,0.9,size=(3,3))/1e4
b11

array([[3.57066e-05, 2.66566e-05, 4.61007e-05],
       [4.93474e-05, 8.19261e-05, 6.83488e-05],
       [7.16072e-05, 4.00351e-05, 3.74992e-05]])

In [79]:
np.set_printoptions(threshold=6)
a12=np.arange(15)
print(a12)
np.set_printoptions(threshold=np.nan)
print(a12)

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [80]:
url = 'iris.data'
iris=np.genfromtxt(url,delimiter=',',dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [81]:
iris=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
iris[:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [82]:
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])#usecols,获取第n列,这里是第0列
np.mean(sepallength)#均值
np.median(sepallength)#中位数
np.std(sepallength)#标准差

0.8253012917851409

In [83]:
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
print(Smax - Smin)
sepallength.ptp()#取最大与最小值之间的差值

3.6000000000000005


3.6000000000000005

In [84]:
np.percentile(sepallength,q=[5,95])

array([4.6  , 7.255])

In [85]:
iris_2d=np.genfromtxt(url,delimiter=',',dtype='object')
#150 ,5
i, j = np.where(iris_2d)#生成每一个数据的坐标，i存放横轴，j存放纵轴
np.random.choice(i,20)
#choice(a, size=None, replace=True, p=None)
#表示从a中随机选取size个数
#replace:是否是放回抽样
#p是每一个元素抽中的概率


array([ 18,  99,  24, 110,  60,  93, 108,  58,  59,  99, 138,  18,  79,
         7, 125,  42,  33,  25, 139,  71], dtype=int64)

In [86]:
iris_2d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)]=np.nan
#iris_2d[~np.isnan(iris_2d)]#取所有非nan的值

In [87]:
iris_2d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
#petallength（第3列）> 1.5 和 sepallength（第1列）< 5.0 的iris_2d行
print((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))
ix=np.where((iris_2d[:,2]>1.5) & (iris_2d[:,0]<5.0))#where可以取出坐标
print(ix)
iris_2d[ix]

[False False False False False False False False False False False  True
 False False False False False False False False False False False False
  True False False False False  True  True False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False]
(array([ 11,  24,  29,  30,  57, 106], dtype=int64),)


array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [88]:
#选择没有任何nan值的iris_2d行。
iris_2d=np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)]=np.nan
#iris_2d[iris_2d[],:]

ix=np.sum(np.isnan(iris_2d),axis=1)
print(np.isnan(iris_2d))

[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [ True False False False]
 [False  True False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [ True False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 [False False False False]
 

In [89]:
iris_2d[ix==0,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3

In [90]:
species = np.array([row.tolist()[4] for row in iris])
# Get the unique values and the counts
np.unique(species, return_counts=True)

IndexError: list index out of range

In [ ]:
# numpy.digitize(x, bins, right = False)

# 参数：

# x : numpy数组

# bins :一维单调数组，必须是升序或者降序

# right：间隔是否包含最右
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# 返回值：x在bins中的位置。

petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])
print(iris[:, 2].astype('float'),petal_length_bin)
# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat

In [101]:
#numpy.random.choice(a, size=None, replace=True, p=None)
#a : 如果是一维数组，就表示从这个一维数组中随机采样；如果是int型，就表示从0到a-1这个序列中随机采样。
# size : 采样结果的数量，默认为1.可以是整数，表示要采样的数量；也可以为tuple，如(m, n, k)，则要采样的数量为m * n * k，size为(m, n, k)。
# replace : boolean型，采样的样本是否要更换？这个地方我不太理解，测了一下发现replace指定为True时，采样的元素会有重复；当replace指定为False时，采样不会重复。
# p : 一个一维数组，制定了a中每个元素采样的概率，若为默认的None，则a中每个元素被采样的概率相同。

#####np.r_是按列连接两个矩阵，就是把两矩阵上下相加，要求列数相等，类似于pandas中的concat()。
#####np.c_是按行连接两个矩阵，就是把两矩阵左右相加，要求行数相等，类似于pandas中的merge()。

# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
#类似arange（）不过linspace可以选择更细的非整数间隔
# 在指定的间隔内返回均匀间隔的数字。
# 返回num均匀分布的样本，在[start, stop]。
# 这个区间的端点可以任意的被排除在外。
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.random.seed(100)
iris[:,4]
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
#probs 按比例生成随机150个从0-1的数
index = np.searchsorted(probs, np.random.random(150))
#从probs中随机选取150个index
species_out = species[index]
#从species中获取这些index的值

# print(np.unique(species_out, return_counts=True))
a=np.unique(species_out, return_counts=False)
dict(zip(np.arange(a.shape[0]),a))
#a, s,p = np.unique(A, return_index=True, return_inverse=True)
#return_index=True表示返回新列表元素在旧列表中的位置，并以列表形式储存在s中。
#return_inverse=True 表示返回旧列表元素在新列表中的位置，并以列表形式储存在p中
#return_counts 返回的第二个矩阵对应于第一个矩阵中元素在b中相应的出现次数。


{0: b'Iris-setosa', 1: b'Iris-versicolor', 2: b'Iris-virginica'}

In [30]:
np.set_printoptions(precision=2)
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(a)
np.clip(a, a_min=10, a_max=30)#小于10的值替换为10，大于30的值替换为30
#np.where(condition, x, y)
#满足条件(condition)，输出x，不满足输出y。

np.where(a < 10, 10, np.where(a > 30, 30, a))
#a<10输出10
#否（a>=10）：如果a>30 输出30 否则 输出a

[27.63 14.64 21.8  42.39  1.23  6.96 33.87 41.47  7.7  29.18 44.67 11.25
 10.08  6.31 11.77 48.95 40.77  9.43 41.   14.43]


array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [31]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
sort_a=a.argsort()
a[sort_a[-5:]]
a[a.argsort()][-5:]

array([41.  , 41.47, 42.39, 44.67, 48.95])

In [33]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [38]:
# def f(arr):
count_arr=[]
for row in arr:
    temp_arr=[0]*arr.shape[1]
    a,c=np.unique(row,return_counts=True)
    for i,j in zip(a,c):
        temp_arr[i-1]=j
    count_arr.append(temp_arr)
    
count_arr
        

[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]