In [182]:
import numpy as np

In [183]:
def loadDataSet():
    data=[
            [4,4,0,2,2],
            [4,0,0,3,3],
            [4,0,0,1,1],
            [1,1,1,2,0],
            [2,2,2,0,0],
            [1,1,1,0,0],
            [5,5,5,0,0]
         ]
    return np.array(data)
def loadDataSet1():
    
#     data=[[0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5],
#            [0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 3],
#            [0, 0, 0, 0, 4, 0, 0, 1, 0, 4, 0],
#            [3, 3, 4, 0, 0, 0, 0, 2, 2, 0, 0],
#            [5, 4, 5, 0, 0, 0, 0, 5, 5, 0, 0],
#            [0, 0, 0, 0, 5, 0, 1, 0, 0, 5, 0],
#            [4, 3, 4, 0, 0, 0, 0, 5, 5, 0, 1],
#            [0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 4],
#            [0, 0, 0, 2, 0, 2, 5, 0, 0, 1, 2],
#            [0, 0, 0, 0, 5, 0, 0, 0, 0, 4, 0],
#            [1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0]]
    data=[[2, 0, 0, 4, 4, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5],
           [0, 0, 0, 0, 0, 0, 0, 1, 0, 4, 0],
           [3, 3, 4, 0, 3, 0, 0, 2, 2, 0, 0],
           [5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0],
           [0, 0, 0, 0, 0, 0, 5, 0, 0, 5, 0],
           [4, 0, 4, 0, 0, 0, 0, 0, 0, 0, 5],
           [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 4],
           [0, 0, 0, 0, 0, 0, 5, 0, 0, 5, 0],
           [0, 0, 0, 3, 0, 0, 0, 0, 4, 5, 0],
           [1, 1, 2, 1, 1, 2, 1, 0, 4, 5, 0]]
    return np.array(data)

In [141]:
#两种皮尔逊相关系数计算方法
def SimMethod(inA,inB):
    if len(inA)<3:
        return 1
    inA=(inA-np.mean(inA)).reshape(1,-1)
    inB=(inB-np.mean(inB)).reshape(-1,1)
    p=inA.dot(inB)[0][0]/(np.sqrt(np.sum(inA**2))*np.sqrt(np.sum(inB**2)))
    return 0.5+0.5*p
    
def pearSim(inA,inB):
    if len(inA)<3: return 1.0
    return 0.5+0.5*np.corrcoef(inA,inB,rowvar=1)[1][0]

def cosSim(inA,inB):
    inA=inA.reshape(1,-1)
    inB=inB.reshape(-1,1)
    p=inA.dot(inB)[0][0]/(np.linalg.norm(inA)*np.linalg.norm(inB))
    return 0.5+0.5*p

In [142]:
data=loadDataSet()
inA=data[:,0]
inB=data[:,4]
print(SimMethod(inA,inB))
print(pearSim(inA,inB))
print(cosSim(inA,inB))

0.7520080643870927
0.7520080643870926
0.8608308675945582


In [137]:
def standEst(data,user,simMeas,item):#预测评分
    simtotal,ratsimtotal=0,0#
    for data_item in data[:,data[user,:]>0].T:#找到所有user行非0列
        lines=np.where((data_item>0)&(data[:,item]>0))[0]#确定某两行的非零行
        if len(lines)==0:
            similarity=0
        else:
            similarity=simMeas(data_item[lines],data[lines,item])
        simtotal+=similarity
        ratsimtotal+=similarity*data_item[user]
    if simtotal==0:
        return 0
    else:
        return ratsimtotal/simtotal

In [181]:
data1=loadDataSet1()
u,s,v=np.linalg.svd(data1)
s[:5].sum()/s.sum()
sig=np.diag(s[:5])
# 利用U矩阵将物品转换到低维空间中，构建转换后的物品(物品+4个主要的特征)
xformedItems = data1.T.dot(u[:, :5]).dot(np.linalg.pinv(sig)) 
print(xformedItems)


[[-0.45137416  0.03084799 -0.00290108  0.01189185 -0.02704996]
 [-0.36239706  0.02584428 -0.00189127  0.01348796 -0.06811097]
 [-0.46879252  0.03296133 -0.00281253  0.01656192 -0.08376713]
 [-0.01007685 -0.34024331 -0.22728592  0.14546051 -0.85218381]
 [-0.01567036 -0.38750193  0.61197998 -0.17137451 -0.04105577]
 [-0.01664563 -0.52000097 -0.3608907  -0.14984063  0.04176534]
 [-0.00474684 -0.18887149 -0.00924222  0.94228361  0.223935  ]
 [-0.46712774  0.00389831  0.03349951 -0.02080674  0.05093596]
 [-0.47223188  0.02853952 -0.00504059  0.00160266  0.07391942]
 [-0.01591788 -0.39205093  0.55707516  0.04356321  0.01628715]
 [-0.0552444  -0.52034959 -0.36330956 -0.19023805  0.44664796]]


In [205]:
def svdEst(data,user,simMeas,item):
    u,s,v=np.linalg.svd(data)
    simtotal,ratsimtotal=0,0#计算式
    X_form=data.T.dot(u[:,:5]).dot(np.linalg.pinv(np.diag(s[:5])))#矩阵降维
    for j in range(data.shape[1]):
        rate=data[user,j]
        if rate==0 or item==j:continue
        similarity=simMeas(X_form[item,:],X_form[j,:])
        simtotal+=similarity
        ratsimtotal+=similarity*rate
    if simtotal==0:
        return 0
    else:
        return ratsimtotal/simtotal           


In [206]:
def recommend(data,user,n=3,simmeas=cosSim,estmehod=standEst):
    zero_ix=np.where(data[user]==0)[0]
    unrate_scores=[]
    for ix in zero_ix:#遍历零列（用户未评级的那一项）
        estimate_score=estmehod(data,user,simmeas,ix)#对未评级的进行评分
        unrate_scores.append((ix,estimate_score))
    l=sorted(unrate_scores,key=lambda x:x[1],reverse=True)
    return l

In [207]:
recommend(data1,1,simmeas=SimMethod,estmehod=svdEst)


[(6, 3.3468801084202875),
 (9, 3.341799823515646),
 (4, 3.336765794121341),
 (8, 3.295801535769996),
 (7, 3.288573039505219),
 (0, 3.2471537903801884),
 (2, 3.218504060438292),
 (1, 3.2161302502426574)]